name: untitled1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.4
  image_picker: ^1.1.2
  http: ^1.2.1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_generative_ai: ^0.4.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash.png.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/splash.png.jpg"

flutter_native_splash:
  color: "#2D3E2D"
  image: "assets/images/splash.png.jpg"
  color_dark: "#1B2612"
  image_dark: "assets/images/splash.png.jpg"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  branding: "assets/images/splash_branding.jpg"
  branding_mode: bottom
  android_12:
    image: "assets/images/splash.png.jpg"
    icon_background_color: "#2D3E2D"
    color: "#2D3E2D"
    color_dark: "#1B2612"
